### ISSUE TITLE
issue w\ input file

### ISSUE THREAD

**Issue by raveancic** [sgravel/tracts#11]
Dear all,
thank you for this tool, I would like to use it on my data but unfortunately I am getting the error 

```
ValueError: chromosome pairs of different lengths!
```

the example is running well, I am thinking that it might be a problem of input file but I am not able to figure out the issue. 
Thank you in advance,
Alessandro

**Comment by sgravel** [comment]
This happens when the length of the two copies of the same chromosome are unequal. This will happen sometimes at the end of chromosomes if you have an uncertain assignment that has been discarded, but it can also be the result of a bug in your ancestry assignment pipeline. 

If the length differences are small, you can likely ignore that warning. If they are large the best course of action depends on the source of the differences.

**Comment by raveancic** [comment]
Dear Simon,
thank you for the fast answer. I checked and it is true, once I removed the unassigned length fragments (should I removed them?) I have high differences in the chromosome length if I compare the hap A and hap B of the same individual. However, I have seen that these differences (lower than the mine) are present also in the example individuals (PUR), is there a threshold to be considered for this difference in length?  

Unfortunately the error is not a warning and it does not allow me to proceed the analysis is there maybe a workaround?

Thanks again,
Alessandro

**Comment by sgravel** [comment]
Can you provide example code? If you just have short unknown segments at the end, these can be assigned using the smoothing functions. If you have very long unknown segments, I would have concerns about applying tracts, since the distribution of tract lengths might be severely affected.

**Comment by sgravel** [comment]
I'll go ahead and mark this as resolved. Let me know if you need more assistance.
